;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagRedirects=(OldTagName="Abilities.Names.DecreaseHealthProjectile1",NewTagName="Abilities.Names.DecreaseHealthProjectile")
+GameplayTagRedirects=(OldTagName="Animations.Character.TakeDamage",NewTagName="Animations.Character.Hit")
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Abilities",DevComment="Defines Tags tied to AbilitySystem ")
+GameplayTagList=(Tag="Abilities.Names",DevComment="")
+GameplayTagList=(Tag="Abilities.Names.DecreaseHealthAOE",DevComment="")
+GameplayTagList=(Tag="Abilities.Names.DecreaseHealthOvertimeProjectile",DevComment="")
+GameplayTagList=(Tag="Abilities.Names.DecreaseHealthProjectile",DevComment="")
+GameplayTagList=(Tag="Abilities.Names.EnergyRestoration",DevComment="")
+GameplayTagList=(Tag="Abilities.Names.HealthRestoration",DevComment="")
+GameplayTagList=(Tag="Abilities.Names.Revive",DevComment="")
+GameplayTagList=(Tag="Abilities.Names.SpeedBuff",DevComment="")
+GameplayTagList=(Tag="Abilities.Slot",DevComment="")
+GameplayTagList=(Tag="Abilities.Slot.Key1",DevComment="")
+GameplayTagList=(Tag="Abilities.Slot.Key2",DevComment="")
+GameplayTagList=(Tag="Abilities.Slot.Key3",DevComment="")
+GameplayTagList=(Tag="Abilities.Slot.Key4",DevComment="")
+GameplayTagList=(Tag="Abilities.Slot.Key5",DevComment="")
+GameplayTagList=(Tag="Animations",DevComment="")
+GameplayTagList=(Tag="Animations.Character",DevComment="")
+GameplayTagList=(Tag="Animations.Character.Death",DevComment="")
+GameplayTagList=(Tag="Animations.Character.Hit",DevComment="")
+GameplayTagList=(Tag="Animations.Character.Resurrect",DevComment="")

